name: Translate Markdown

on:
  push:
    branches:
      - main

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Translate Markdown files
        uses: 3ru/gpt-translate@main  # Assume que gpt-translate suporta tradução diretamente
        with:
          input_filepath: '*.md'  # Este é um exemplo, você precisará especificar o caminho correto
          output_filepath: '*_PT_BR.md'  # Este é um exemplo, você precisará especificar o caminho correto
          target_language: 'pt-BR'
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}  # Supondo que você tenha configurado sua chave API como um segredo do repositório

